# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solutionName: 'MyFramework.IO.sln'
  solutionFolder: 'MyFramework.IO'

stages:
- stage: Build
  displayName: 'Build and Test Artifact'
  jobs:
    - job: Build
      displayName: 'Build and Test Artifact'
      
      steps:

        - task: DotNetCoreCLI@2
          displayName: 'Restore NuGet packages'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
            feedsToUse: 'select'
            verbosityRestore: 'Normal'

        - task: SonarQubePrepare@4
          inputs:
            SonarQube: 'sonarcloud'
            scannerMode: 'MSBuild'
            projectKey: 'lang-codes_myframework-io'
            projectName: 'sonar.projectName'

        - task: DotNetCoreCLI@2
          displayName: 'Build solution'
          inputs:
            command: 'build'
            projects: '$(solutionFolder)/$(solutionName)'

        - task: DotNetCoreCLI@2
          displayName: 'Run Unit/Integration Tests'
          inputs:
            command: 'test'
            projects: '$(solutionFolder)/$(solutionName)'

        - task: SonarQubeAnalyze@4

        - task: SonarQubePublish@4
          inputs:
            pollingTimeoutSec: '300'